### ISSUE TITLE
Issue with false response 

### ISSUE THREAD

**Issue by LunartechTeam** [ssovit/TikTok-API-PHP#36]
I implemented this Api on one of my App. It was working perfectly but after some days, it started returning false. I wasn't using any proxy when it was working, but now i used proxy but still wasn't working.
Php version:7.3
![Screenshot_20210529-150240_Chrome](https://user-images.githubusercontent.com/74169168/120073297-9eae2000-c08f-11eb-8dd8-6eaf54c3e88b.jpg)

**Comment by ssovit** [comment]
Hello,

1. Don't change the base class. instead create instance like `$tiktok=new \Sovit\TikTokApi()`. Follow examples in `examples` folder
2. Use good proxy. Rotating proxy is better.
3. Don't share your proxy detail in public.

Library is working fine as I tested it few moments back. Your issue is probably with your proxy.
